# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 568bd6acfa96fa2bbf0712a4c8a21b8dd3550498a1b0d7cbf9c19ff78956e3c00391d8d25647a6ae6a88d7ac4f00802c1fc2f6ec2b9c57114898639514683b7f
  google_civics_api_key: <%= ENV['GOOGLE_CIVICS_API_KEY'] %>
  google_oauth2_app_id: 845424102836-ana9i2hk0e4a5b64uc1sqj4sndnvghll.apps.googleusercontent.com
  google_oauth2_app_secret: F1xhOzg4L5Hvu4qw9xX3oC2W
  twitter_oauth2_app_id: asdf
  twitter_oauth2_app_secret: asdf
  facebook_oauth2_app_id: 1718391995157154
  facebook_oauth2_app_secret: 276d617b28a79a7a36d5818c0869d507

test:
  secret_key_base: 91270ec01d45c0074e9eacdbbaff4273c0388fe53ebab5334e6d515cb73c3deada94866c6f754761443d4115a81867955b5273d317e586b214e8e0a443d1e976
  google_civics_api_key: <%= ENV['GOOGLE_CIVICS_API_KEY'] %>
  google_oauth2_app_id: 845424102836-ana9i2hk0e4a5b64uc1sqj4sndnvghll.apps.googleusercontent.com
  google_oauth2_app_secret: F1xhOzg4L5Hvu4qw9xX3oC2W
  twitter_oauth2_app_id: asdf
  twitter_oauth2_app_secret: asdf
  facebook_oauth2_app_id: 1718391995157154
  facebook_oauth2_app_secret: 276d617b28a79a7a36d5818c0869d507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_civics_api_key: <%= ENV['GOOGLE_CIVICS_API_KEY'] %>
  google_oauth2_app_id: <%= ENV['GOOGLE_OAUTH2_APP_ID'] %>
  google_oauth2_app_secret: <%= ENV['GOOGLE_OAUTH2_APP_SECRET'] %>
  twitter_oauth2_app_id: <%= ENV['TWITTER_OAUTH2_APP_ID'] %>
  twitter_oauth2_app_secret: <%= ENV['TWITTER_OAUTH2_APP_SECRET'] %>
  facebook_oauth2_app_id: <%= ENV['FACEBOOK_OAUTH2_APP_ID'] %>
  facebook_oauth2_app_secret: <%= ENV['FACEBOOK_OAUTH2_APP_SECRET'] %>
